# Generated by Django 3.2.13 on 2022-05-20 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.AddField(
            model_name='exam',
            name='examid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(db_column='questionid', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='exam',
            field=models.ForeignKey(db_column='examid', on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
