# Generated by Django 3.2.13 on 2022-05-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='highest',
            field=models.BooleanField(default=False),
        ),
    ]
